# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 065a45be2c7d0755663448254b270faef21e1d90ae29f72fca371dbd045400eaff92c92d37c3f2347de2a0be1fbd7f6fb90591a9c2d1e2a64ad89369271764d7

test:
  secret_key_base: 04e4d0bbde4d14b953352d2e47b545da3cb821a8fce79616cc49422d386681c5a1847d1db1bd372077235da10a02f0ad61b9b73018b747134ba555c3f9513d52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
